### ISSUE TITLE
Different outputs: voxcraft-sim and reconfigurable_organisms

### ISSUE THREAD

**Issue by biagzi** [voxcraft/voxcraft-sim#41]
This simulator gives different outputs from the reconfigurable_organisms (https://github.com/skriegman/reconfigurable_organisms) simulator for the same vxa file. 
Shouldn't it be the same?

Behavior in reconfigurable_organisms VoxCad simulator:

https://user-images.githubusercontent.com/59887998/108722291-c2e2e980-7501-11eb-9315-cc340a7fe99e.mp4

Behavior in voxcraft-sim VoxCad simulator:

https://user-images.githubusercontent.com/59887998/108722435-eb6ae380-7501-11eb-8a6b-0c6adc556df6.mp4

**Comment by skriegman** [comment]
Hi @biagzi 
I wouldn't expect any two simulators to match out of the box. But this is a very nice example. It is small enough that we might be able to analyze the difference. It looks like the amplitude / phase offsets aren't read / utilized in the same way. However, it is impossible to say without reproducing your videos. Can you provide some more information so we can replicate it?

https://github.com/voxcraft/voxcraft-sim/blob/master/readme_before_reporting_issues.md

**Comment by skriegman** [comment]
Oh wait! this is not voxcraft-sim. This issue is in the wrong place. 

This is a question about [voxcraft-viz](https://github.com/voxcraft/voxcraft-viz/issues) which is a fork voxCAD. The only thing we added is a mechanism for replaying behavioral history files simulated using voxcraft-sim, since many users do not have a local GPU.

You are actually asking why the behavior is not the same in the two versions of voxcad. The default version and the version used in reconfigurable organisms. That is because there is no phase offset in voxcad / voxcraft-viz. I added phase offset in the reconfigurable organisms fork of voxcad. 

There are phase offsets in voxcraft-sim, however. So if you simulated the same robot in voxcraft-sim and the reconfigurable organisms repos, you should see the same, or very similar behavior.

**Comment by biagzi** [comment]
Sorry for post in the wrong place!
I will try to simulate in voxcraft-sim. 
Thank you for your help and for the nice software!

**Comment by skriegman** [comment]
@biagzi no need to apologize. The docs are not as clear as we'd like them to be. I am personally struggling to keep up with the software development. We are looking for more contributors to the software and docs. If you have a suggestion, please submit a pull request. Good luck.
