### ISSUE TITLE
Able to rotation of a singleton to provide more possibility for attachment

### ISSUE THREAD

**Issue by liusida** [voxcraft/voxcraft-sim#8]
Now attachment only happens between voxels with similar orientation. That's not enough.

But I failed to do arbitrary attachment last week, so a possible mediator is only rotating singletons to make things align during checking for attachment.

Start branching out and working on this.

**Comment by skriegman** [comment]
With axis aligned attachment, we basically just 2D bodies. If piles can be identified as 2D bodies, then they could be rotated with the same mechanism as rotating a pair. Right?

**Comment by skriegman** [comment]
@liusida With axis aligned attachment, we basically just get 2D bodies. If piles can be identified as 2D bodies, then they could be rotated with the same mechanism as rotating a pair. Right?

**Comment by skriegman** [comment]
Instantaneous rotation voxel singletons and pairs works very well using the detach-rotate-reattach method. Because everything is axis aligned, the same rotation method could be applied to all attachments (not just pairs, not just 2d bodies--all bodies!).

The problem is that the rotations slowed down the evaluations 10x for the bulldozers. Is it possible to speed it up?>

**Comment by skriegman** [comment]
Instantaneous rotation of voxel singletons / pairs works very well using the detach-rotate-reattach method. Because everything is axis aligned, the same rotation method could be applied to all attachments (not just pairs, not just 2d bodies--all bodies!). Right @liusida? 

The problem is that including rotations slowed the evaluations of the bulldozers too much (10x slower). Is it possible to speed it up?>
