### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#9]
I thought I had voxcraft-sim working, but opening up my history file, I get this:

1 GPU found.
=== set device to 0 for 1 simulations ===

Total GPU memory 4239785984 bytes.
Set GPU heap size to be 2119892992 bytes.

/home/rieffelj/src/voxcraft-sim/src/VX3/VX3_SimulationManager.cu(413): CUDA Function Error: invalid device function 
Running simulation locally by default.
./vx3_node_worker -i workspace/locally/20200625155235.vxt -o workspace/locally/20200625155235.vxr

**Comment by davidmatthews1uvm** [comment]
Which GPU do you have? This error could be caused by compiling for the wrong generation of GPU. We are targeting Pascal and newer GPUs in the CMakeLists.txt file. Our team does not have access to older GPUs to test on, but we expect that it should run on GPUs with Compute Capability 3.5 or better (https://en.wikipedia.org/wiki/CUDA for specific models).

**Comment by jrieffel** [comment]
(base) rieffelj@Mille-Feuille:~/src/voxcraft-sim/build$ lspci | grep NVIDIA
02:00.0 VGA compatible controller: NVIDIA Corporation GM107GL [Quadro K1200] (rev a2)
02:00.1 Audio device: NVIDIA Corporation Device 0fbc (rev a1)

**Comment by davidmatthews1uvm** [comment]
Your GPU is compute capability 5.0 which has not yet been tested with Voxcraft-sim but is expected to work. We need to modify the 
[CMakeLists.txt](https://github.com/voxcraft/voxcraft-sim/files/4833711/CMakeLists.txt) so that it targets a compute capability older than 6.0. The above is a modified CMakeLists.txt file.

**Comment by jrieffel** [comment]
Success, thank you!
